### ISSUE TITLE
site disappears after visiting blog page

### ISSUE THREAD

**Issue by hiMaisie** [hiMaisie/personal-site#19]
visiting the blog page, causes the site to disappear to a black screen momentarily. 

https://mbell-api.glitch.me/posts/

returns an internal server error, which is causing the `map()` method to fail on `Blog.jsx`, line 36.

* fix API to not do that
* fix frontend to not fail when it can't parse the API.

**Comment by hiMaisie** [comment]
server error (glitch.com):

```
{ Error: certificate has expired
4:23 PM
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
4:23 PM
    at emitNone (events.js:106:13)
4:23 PM
    at TLSSocket.emit (events.js:208:7)
4:23 PM
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
4:23 PM
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
4:23 PM
  code: 'CERT_HAS_EXPIRED',
4:23 PM
  config: 
4:23 PM
   { url: 'https://blog.mbell.dev/ghost/api/v3/content/posts/',
4:23 PM
     method: 'get',
```

**Comment by hiMaisie** [comment]
strange because the cert for `blog.mbell.dev` is very much not expired

**Comment by Snuggle** [comment]
Good luck fixing this, I hope my report helped! 😅

**Comment by hiMaisie** [comment]
found the fix! https://support.glitch.com/t/curl-cant-connect-to-letsencrypt-sites-anymore/47111/3
